name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Backend Build
      - name: Install Backend Dependencies
        run: |
          npm ci
          
      - name: Build Backend
        run: |
          cd backend
          npm run build:prod
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          PORT: ${{ secrets.PORT }}
          MAILGUN_KEY: ${{ secrets.MAILGUN_KEY }}
          API_KEY: ${{ secrets.API_KEY }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

      # Frontend Build
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      - name: Build Frontend
        run: |
          cd frontend
          npm run build:prod

      # Deploy to Vercel
      - name: Deploy Frontend to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod --yes'
          working-directory: ./frontend